### ISSUE TITLE
Babel translation

### ISSUE THREAD

**Issue by UAVova** [stoffern/pokemongo-api#105]
I need help with compiling (or probaby translating) code from babel to normal js. When i try to do so using: [https://babeljs.io/repl/](https://babeljs.io/repl/) and run output with `node example.js` it throws an error:
 `error  Unexpected token import`
Another thing i can't understand is that i can't actually run command `babel-node example.js` or `node-babel example.js`. It's saying that there is no such command.. However, npm run example working just fine...

Why i need working babel -> js translation? - I want to compile example to 1 exe (with nexe or another package).

I know that it is probably not the best section for this kind of issue, but i need your help guys. Also, there is no forum..

**Comment by stoffern** [comment]
javascript as you know it is version ES5 .
We are running ES6, the next generation javascript. since all browsers and node dont support es6 yet you need babel to translate ES6 into ES5. you can also compile ES6 into ES5 with babel.

if you cant run babel-node then try to run: `node_modules\.bin\babel-node example.js`
This has to do with your configuration.

Try this example if you need start help:
https://github.com/stoffern/pokemongo-api/issues/66#issuecomment-235335609

**Comment by UAVova** [comment]
s
