### ISSUE TITLE
Feature request?

### ISSUE THREAD

**Issue by Upguard** [stoffern/pokemongo-api#79]
It would be nice if we could set a radius, have the script take a lat/long and jump around within that radius to get all pokemon/gyms/stops. We already have the cells, could we not get the lat/long from those cells and have our "character" jump to those cells to get additional data?

The only way I was able to do something similar (I'm a beginner when it comes to coding) was to expand the "meters" within the getRandomDirection function - where it says 600. The only problem with this is it's random, and doesn't exactly do a "radius" type search.

```
function getRandomDirection(){
  let latMorP = Math.random() < 0.5 ? -1 : 1
  let longMorP = Math.random() < 0.5 ? -1 : 1

  let latitude = ((Math.floor((Math.random() * 600) + 1))/100000)*latMorP
  let longitude = ((Math.floor((Math.random() * 600) + 1))/100000)*longMorP

  return {latitude, longitude}
}
```

**Comment by stoffern** [comment]
You can not travel over 20meters every 3 second or you get banned. And the normal heartbeat is every 3 sec. Poke.player.walkAround() will do a random lat,long travel to a distance. 1-15meters.

**Comment by Upguard** [comment]
How are these websites like pokevision getting all the pokemon within a certain radius? I'm not all that worried about getting banned, I don't plan on actually playing the game, I'm just trying to build a map that shows pokemon in a certain radius. 

There's ways around the ban issue.

**Comment by AutomatonSystems** [comment]
Scanning of all pokemon in a radius around a point is actually pretty complex because the radius that the pokemon servers let you 'see' is fixed. Sites like pokevision, as you have guessed, teleport the player around in a grid/spiral pattern to scan the whole area. Have a look at https://github.com/mchristopher/PokemonGo-DesktopMap which is a desktop app, if you enable the scanned areas display you can see the spiral pattern of scans needed to 'scan' a certain radius.

Repeating that via this API you'll need to calculate the list of co-ordinates for each point, and for each point teleport the player via `player.setLocation(lat,lng)` and then scan via `Poke.GetMapObjects()`, adding the found pokemon to a list/plotting them on a map as you go.

As far as I can tell the focus of this API is more about creating bots that play the game like a human would (rather than scanning/map hack bots). You might be better trying to find a more mapping focused API, particularly as most of these will already have mapping display built in.

**Comment by Upguard** [comment]
I've got a few ideas on how to accomplish this. I'm going to try to implement the code today. I'll update this thread if I succeed.

**Comment by stoffern** [comment]
This is possible.
If you really dont need a circle here is a solution to a square
```
async square(lat,long,lat2,long2){
  for (; lat < lat2; lat+0.0002) { 
    for (; long < long2; long+0.0002) { 
      res = await Poke.GetMapObjects()
      Object.assign(objects, res)
    }
  }
  return objects
}

await square(0.10,0.20,0.20,0.30)
```
just be creative! :smile: 
closing thisone as the feature is not needed in the API but can be created in a standalone script

**Comment by Upguard** [comment]
Stoffern, thank you! This will come in handy.

**Comment by stoffern** [comment]
Oh, I forgot the player.setLocation(lat,long) before mapObjects :)

**Comment by Upguard** [comment]
No problem, I figured that out :P
