### ISSUE TITLE
Multiple API instances

### ISSUE THREAD

**Issue by InsOpDe** [stoffern/pokemongo-api#90]
Ive tried to run this API with two users. As it run I got very often "Illegal Buffer" errors, so I wondered whether maybe the Data received/sent got somewhat intersected. Well i did create new API/auth instances, so its rather not a javascript/node problem. 
**My guess is that since im using the same settings.js-data for both accounts, maybe the server gets irritated**
I even got softbanned, even tho I did not teleport for more than 20m.
Then again: you guys all use the same settings.js-data (so maybe its linked to my ip-adress, too?)
A solution would be to have another set of data for things like `ANDROID_ID`

**Comment by stoffern** [comment]
The ANDROID_ID is the id of the Pokemon Go id at Google Accounting that you need to logon to.
If we change this you will login to different service, not Pokemon Go.
The settings file is more or less fixed values for the API

I would guess they track 2 different devices at the same time from the same IP on different GEO locations.
This is not possible in real life. Then you need a proxy on your accounts so that they have different IP :smile: 
This feature we are working on :smile:

**Comment by stoffern** [comment]
@InsOpDe this is linked to the `Illegal buffer` #84 
closing this thread
